spring:
  profiles:
    group:
      stage: stageDB, jasypt, oauth2, jwt
      prod:
      test:
    active: stage

# JPA Log
logging:
  level:
    org:
      hibernate:
        sql: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
